server:
  port: 8002

spring:
  datasource:
    url : jdbc:mysql://106.52.110.165:3306/blog_base?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username : root
    password : testadmin
    driverClassName : com.mysql.cj.jdbc.Driver
