server:
  port: 8002

spring:
  datasource:
    url : jdbc:mysql://localhost:3311/blog_base?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username : root
    password : root
    driverClassName : com.mysql.cj.jdbc.Driver
